name: "Speech_To_Text_Finetuning"

# use `init_from_nemo_model` or `init_from_pretrained_model` to initialize the model
# We do not currently support `init_from_ptl_ckpt` to create a single script for all types of models.
init_from_nemo_model: "/home/mateusz/PycharmProjects/metal-to-text/model/parakeet-rnnt-0.6b.nemo" # path to nemo model

model:
  sample_rate: 16000
  compute_eval_loss: false # eval samples can be very long and exhaust memory. Disable computation of transducer loss during validation/testing with this flag.
  log_prediction: true # enables logging sample predictions in the output during training
  rnnt_reduction: 'mean_volume'
  skip_nan_grad: false
  change_vocabulary: true
  gradient_checkpointing: true
#  cpu_offloading: true
#  cpu_offloading_weights: true
#  cpu_offloading_num_layers: 59
  use_precision_aware_optimizer: true
  recompute_granuality: full
  recompute_method: block
  recompute_num_layers: 8
  transformer_engine: true
  sequence_parallel: true

  train_ds:
    manifest_filepath: "/home/mateusz/PycharmProjects/metal-to-text/data/train_data_8.jsonl"
    sample_rate: ${model.sample_rate}
    batch_size: 1 # you may increase batch_size if your memory allows
    shuffle: true
    num_workers: 0
    pin_memory: true
    max_duration: 240
    min_duration: 0.1

    # tarred datasets
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    # bucketing params
    bucketing_strategy: "fixed"
    bucketing_batch_size: null

  validation_ds:
    manifest_filepath: "/home/mateusz/PycharmProjects/metal-to-text/data/valid_data_1.jsonl"
    sample_rate: ${model.sample_rate}
    batch_size: 1
    shuffle: false
    use_start_end_token: false
    num_workers: 0
    pin_memory: true

  test_ds:
    manifest_filepath: "/home/mateusz/PycharmProjects/metal-to-text/data/test_data_1.jsonl"
    sample_rate: ${model.sample_rate}
    batch_size: 1
    shuffle: false
    use_start_end_token: false
    num_workers: 0
    pin_memory: true

  char_labels: # use for char based models
    update_labels: false
    labels: null # example list config: \[' ', 'a', 'b', 'c'\]

  tokenizer: # use for spe/bpe based tokenizer models
    update_tokenizer: true
    dir: "/home/mateusz/PycharmProjects/metal-to-text/model/model_tokenizer"  # path to directory which contains either tokenizer.model (bpe) or vocab.txt (for wpe)
    type: bpe  # Can be either bpe (SentencePiece tokenizer) or wpe (WordPiece tokenizer)

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 2 # set to zero to disable it
    time_masks: 10 # set to zero to disable it
    freq_width: 27
    time_width: 0.05

  optim:
    _target_: deepspeed.ops.adam.DeepSpeedCPUAdam   # lub deepspeed.ops.adam.FusedAdam
    lr: 1e-4
    betas: [ 0.9, 0.98 ]
    weight_decay: 1e-3

    #    name: adamw
#    lr: 1e-4
#    # optimizer arguments
#    betas: [0.9, 0.98]
#    weight_decay: 1e-3

    # scheduler setup
    sched:
      name: CosineAnnealing
      # scheduler config override
      warmup_steps: 5000
      warmup_ratio: null
      min_lr: 5e-6

trainer:
  devices: -1
  num_nodes: 1
  max_epochs: 50
  max_steps: -1
  val_check_interval: 1.0
  accelerator: gpu
  strategy: deepspeed_stage_3_offload




  accumulate_grad_batches: 8
  gradient_clip_val: 1.0
  precision: bf16-mixed  # 16, 32, or bf16
  log_every_n_steps: 10  # Interval of logging.
  enable_progress_bar: True
  num_sanity_val_steps: 0 # number of steps to perform validation steps for sanity check the validation process before starting the training, setting to 0 disables it
  check_val_every_n_epoch: 1 # number of evaluations on validation every n epochs
  sync_batchnorm: true
  enable_checkpointing: False  # Provided by exp_manager
  logger: false  # Provided by exp_manager
  benchmark: false # needs to be false for models with variable-length speech input as it slows down training


exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    # in case of multiple validation sets, first one is used
    monitor: "val_wer"
    mode: "min"
    save_top_k: 5
    always_save_nemo: True # saves the checkpoints as nemo files along with PTL checkpoints
  resume_if_exists: false
  resume_ignore_no_checkpoint: false

  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null