from pathlib import Path

# Absolute path to the repository root on the training machine.
# Other paths in this file are either derived from it or intentionally kept
# identical to the legacy values already used in the repo.
project_root = Path("/home/mateusz/PycharmProjects/metal-to-text")

# Time budget for test runs in seconds.
timeTest = 15 * 60

# Time budget for training runs in seconds.
timeTraining = 2 * 60 * 60

# Directory where preprocessing writes train/valid/test NeMo manifests.
data_path = str(project_root / "data")

# Directory where raw downloaded songs and music.json are stored.
music_path = str(project_root / "music")

# Directory that contains training assets such as tokenizer outputs and .nemo models.
model_dir = str(project_root / "model")

# Directory where tokenizer_extract.py saves an extracted tokenizer.
tokenizer_dir = str(project_root / "model" / "model_tokenizer")

# Path to the base .nemo model used by both training and tokenizer extraction.
training_nemo_model_path = str(project_root / "model" / "parakeet-rnnt-0.6b.nemo")

# Directory for final vocal-only wav files produced by music_preprocess.py.
final_music_path = "./final_music"

# Temporary directory used by audio-separator during preprocessing.
tmp_path = "./tmp"

# Path to the metadata file created by music_download.py.
music_metadata_path = str(Path(music_path) / "music.json")

# Path to the test manifest generated by preprocessing.
test_manifest_path = str(Path(data_path) / "test_data_1.jsonl")

# Path to the train manifest generated by preprocessing.
train_manifest_path = str(Path(data_path) / "train_data_8.jsonl")

# Path to the validation manifest generated by preprocessing.
valid_manifest_path = str(Path(data_path) / "valid_data_1.jsonl")

# Spotify playlist URL used as the default downloader input.
music_url = "https://open.spotify.com/playlist/3D1d7lpo4fwIxOGNKXDHv4?si=8e4ef642c8cc40cf"

# Ollama model name used to sanitize downloaded lyrics.
model = "qwen2.5:14b-instruct-q4_K_M"

# Genius API token used by spotdl lyric providers.
genius_token = "alXXDbPZtK1m2RrZ8I4k2Hn8Ahsd0Gh_o076HYvcdlBvmc0ULL1H8Z8xRlew5qaG"

# URL of the local Ollama server used during preprocessing.
ollama_url = "http://127.0.0.1:11434"


def get_project_root() -> str:
    return str(project_root)


def get_ollama_url() -> str:
    return ollama_url


def get_model() -> str:
    return model


def get_music_url() -> str:
    return music_url


def get_data_path() -> str:
    return data_path


def get_time() -> tuple[int, int]:
    return timeTraining, timeTest

def get_genius_token() -> str:
    return genius_token


def get_music_path() -> str:
    return music_path


def get_model_dir() -> str:
    return model_dir


def get_tokenizer_dir() -> str:
    return tokenizer_dir


def get_training_nemo_model_path() -> str:
    return training_nemo_model_path


def get_tokenizer_extract_model_path() -> str:
    return training_nemo_model_path


def get_final_music_path() -> str:
    return final_music_path


def get_tmp_path() -> str:
    return tmp_path


def get_music_metadata_path() -> str:
    return music_metadata_path


def get_test_manifest_path() -> str:
    return test_manifest_path


def get_train_manifest_path() -> str:
    return train_manifest_path


def get_valid_manifest_path() -> str:
    return valid_manifest_path
